"use client";

import MaterialIcon from "@/components/material-icon";
import { WorkoutSession } from "@/lib/types";

function formatDuration(seconds: number): string {
  return seconds >= 60 ? `${Math.floor(seconds / 60)}m${seconds % 60 ? ` ${seconds % 60}s` : ""}` : `${seconds}s`;
}

export default function CompletedStretchRoutineDetailModal({ session, onClose }: { session: WorkoutSession; onClose: () => void }) {
  const stretches = (session.stretches ?? []).slice().sort((a, b) => a.sortOrder - b.sortOrder);
  const totalSeconds = stretches.reduce((total, stretch) => total + stretch.holdSeconds, 0);
  const completedDate = session.completedAt ? new Intl.DateTimeFormat(undefined, { weekday: "long", month: "long", day: "numeric", year: "numeric" }).format(new Date(session.completedAt)) : "Completed";

  return <div role="dialog" aria-modal="true" aria-label={`${session.workoutNameSnapshot} history`} style={{ position: "fixed", inset: 0, zIndex: 71, overflow: "hidden", background: "var(--background)" }}><div className="completed-workout-detail-sheet"><header className="completed-workout-detail-header"><div className="flex items-center justify-between" style={{ gap: 12 }}><button type="button" onClick={onClose} aria-label="Close stretch routine history" className="workout-preview-icon-button"><MaterialIcon name="close" size={22} /></button><span style={{ color: "var(--secondary)", fontSize: 12, fontWeight: 850, letterSpacing: "0.08em", textTransform: "uppercase" }}>Stretching history</span><span style={{ width: 42 }} /></div></header><main className="completed-workout-detail-content" style={{ paddingBottom: 30 }}><p style={{ margin: "0 0 8px", color: "#2e9a5b", fontSize: 11, fontWeight: 850, letterSpacing: "0.09em", textTransform: "uppercase" }}>Completed</p><h1 style={{ margin: "0 0 12px", color: "var(--primary)", fontSize: 29, fontWeight: 850 }}>{session.workoutNameSnapshot}</h1><div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 22 }}><span className="completed-workout-stat"><MaterialIcon name="calendar_today" size={14} />{completedDate}</span><span className="completed-workout-stat"><MaterialIcon name="self_improvement" size={15} />{stretches.length} stretches · {formatDuration(totalSeconds)}</span></div>{session.stretchRoutineDescriptionSnapshot && <p className="workout-preview-description">{session.stretchRoutineDescriptionSnapshot}</p>}<h2 style={{ margin: "0 0 11px", color: "var(--primary)", fontSize: 15, fontWeight: 850 }}>Completed routine</h2><div className="flex flex-col" style={{ gap: 9 }}>{stretches.map((stretch, index) => <article key={`${stretch.stretchId}-${index}`} style={{ padding: "14px", border: "1px solid var(--border)", borderRadius: 15, background: "var(--surface)" }}><div className="flex items-start" style={{ gap: 11 }}><span style={{ width: 28, height: 28, display: "grid", placeItems: "center", flexShrink: 0, borderRadius: 9, background: "var(--surface-variant)", color: "var(--secondary)", fontSize: 12, fontWeight: 850 }}>{index + 1}</span><div style={{ minWidth: 0, flex: 1 }}><div className="flex items-start justify-between" style={{ gap: 8 }}><h3 style={{ margin: 0, color: "var(--primary)", fontSize: 15, fontWeight: 850 }}>{stretch.stretchNameSnapshot}</h3><span style={{ color: "#2e9a5b", fontSize: 12, fontWeight: 850 }}>{formatDuration(stretch.holdSeconds)}</span></div><p style={{ margin: "6px 0 0", color: "var(--secondary)", fontSize: 13, lineHeight: 1.45 }}>{stretch.summarySnapshot}</p></div></div></article>)}</div></main></div></div>;
}
